ui: tape
browsers:
  - name: chrome
    version: '-2..latest'
  - name: firefox
    version: '-2..latest'
  - name: safari
    version: '-2..latest'
  - name: iphone
    version: '7.0..latest'
  - name: android
    version: [4.4, 'latest']
  - name: internet explorer
    version: '11'
  - name: microsoftedge
    version: 'latest'
scripts:
  - './node_modules/pouchdb/dist/pouchdb.js'
  - './node_modules/pouchdb/dist/pouchdb.memory.js'
  - './dist/pouchdb-hoodie-api.js'
